import { images } from "../../assets/img";

export const menuList = [
    {
        img: images?.egg,
        title: 'Kung Pao Potato',
        cost: 'Rs. 120.00',
        type: 'Lunch Box',
        desc: 'Mildly spiced indian buttermilk with mint flavor…',
        ratings: '4.6',
        totalratings: '500+ ratings',
        timings:'20-30 mins',
        delivery:'Delivery Time',
    },
    {
        img: images?.icecream,
        title: 'Kung Pao Potato',
        cost: 'Rs. 120.00',
        type: 'Lunch Box',
        desc: 'Mildly spiced indian buttermilk with mint flavor…',
        ratings: '4.6',
        totalratings: '500+ ratings',
        timings:'20-30 mins',
        delivery:'Delivery Time',
    },
    {
        img: images?.egg,
        title: 'Kung Pao Potato',
        cost: 'Rs. 120.00',
        type: 'Lunch Box',
        desc: 'Mildly spiced indian buttermilk with mint flavor…',
        ratings: '4.6',
        totalratings: '500+ ratings',
        timings:'20-30 mins',
        delivery:'Delivery Time',
    },
    {
        img: images?.icecream,
        title: 'Kung Pao Potato',
        cost: 'Rs. 120.00',
        type: 'Lunch Box',
        desc: 'Mildly spiced indian buttermilk with mint flavor…',
        ratings: '4.6',
        totalratings: '500+ ratings',
        timings:'20-30 mins',
        delivery:'Delivery Time',
    },
    {
        img: images?.egg,
        title: 'Kung Pao Potato',
        cost: 'Rs. 120.00',
        type: 'Lunch Box',
        desc: 'Mildly spiced indian buttermilk with mint flavor…',
        ratings: '4.6',
        totalratings: '500+ ratings',
        timings:'20-30 mins',
        delivery:'Delivery Time',
    },
    {
        img: images?.icecream,
        title: 'Kung Pao Potato',
        cost: 'Rs. 120.00',
        type: 'Lunch Box',
        desc: 'Mildly spiced indian buttermilk with mint flavor…',
        ratings: '4.6',
        totalratings: '500+ ratings',
        timings:'20-30 mins',
        delivery:'Delivery Time',
    },
]